### ISSUE TITLE
Incompatibility with Quilt

### ISSUE THREAD

**Issue by qwerty121123** [MoonflowerTeam/pollen#69] opened 2022-11-29 21:29 UTC
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
1 Have the latest 1.18.2 quilt loader version,
2. Attempt to launch with Pollen api.

latest.log: https://pastebin.com/1isPLfme
```

### latest.log

```shell
//look above for pastebin link
```

**Comment by qwerty121123** [comment] 2022-11-29 21:30
Same as #68

**Comment by jacksonhardaway** [comment] 2022-11-29 21:32
Duplicate of #68

**Closed as completed by jacksonhardaway** 2022-11-29 21:32 UTC
