### ISSUE TITLE
Crash upon loading 

### ISSUE THREAD

**Issue by thelegitdolt** [MoonflowerTeam/pollen#34] opened 2022-05-05 06:31 UTC
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
1. Open the game...? I guess? must be some mod incompat or something like that
```

### latest.log

```shell
https://gist.github.com/thelegitdolt/4a922b178a63139ea1726bb0c1cbe2d6

also here's the carsh report as well https://gist.github.com/thelegitdolt/55069ef0348f34f734d382439017eb66


and yeah it does fix it self if I remove pollen
```

**Comment by jacksonhardaway** [comment] 2022-05-05 07:33
The crash log doesn't provide enough info. I assume this is caused by a mod conflicting with Pollen, if you could find that.

**Comment by thelegitdolt** [comment] 2022-05-07 01:00
alr i'll see

**Comment by thelegitdolt** [comment] 2022-05-07 01:03
it's with https://www.curseforge.com/minecraft/mc-mods/debugify

**Comment by thelegitdolt** [comment] 2022-05-07 01:03
oops false alarm debugify isn't it

**Comment by thelegitdolt** [comment] 2022-05-07 01:36
the issue is caused by the 1.18.2 beta of neapolitan

**Comment by thelegitdolt** [comment] 2022-05-07 01:38
my mistake it's with blueprint

**Comment by thelegitdolt** [comment] 2022-05-07 01:42
just to clarify, it is the 1.18.2 beta of neapolitan causing the problem, i've said some contradictory things before cuz i was having issues with testing but it is 100% the 1.18.2 neapolitan beta

**Comment by Ocelot5836** [comment] 2022-05-08 19:14
I tried reproducing the issue, but I can't get the game to crash. I'm using Forge 40.1.0, blueprint 5.3.2 off of curseforge, neapolitan from the 1.18 GitHub branch, and pollen Forge 1.4.1 off of curseforge. Can you verify it still crashes with only pollen, blueprint, and  neapolitan?

**Comment by thelegitdolt** [comment] 2022-05-09 08:31
Does not crash for me anymore either. I swear in my testing yesterday a client with only Neapolitan, pollen and blueprint crashed - and now even running it my full modpack doesn’t crash anymore. I might have accidentally used the 1.4.0 version in my testing, but I’m not 100% sure. I’ll reopen this issue if it comes up again. Sorry!

**Comment by thelegitdolt** [comment] 2022-05-11 01:44
annnnnnd i'm running into this problem again

**Comment by thelegitdolt** [comment] 2022-05-11 01:46
i'll test later just wanted to let you guys know

**Comment by thelegitdolt** [comment] 2022-05-13 02:40
i just got this exact crash without pollen, so i don't think it's an issue from here. it seems to intermittently fix itself anyways, doubt this is a problem with a mod and more eone with my computer... closing for now, sorry for the inconvenience

**Comment by thelegitdolt** [comment] 2022-05-14 21:29
actuallyi mighta s well just keep this open in case something wild comes to you guys later

**Comment by Ocelot5836** [comment] 2022-05-15 02:02
I think this may be fixed now, but I'm not 100% sure. I'll leave this open until we can guarantee it's fixed.

**Comment by cream280** [comment] 2022-05-16 20:38
Same issu
[crash-2022-05-17_04.05.50-client.txt](https://github.com/MoonflowerTeam/pollen/files/8703298/crash-2022-05-17_04.05.50-client.txt)
e

**Comment by Sooperfish** [comment] 2022-05-24 04:46
I have the above mentioned datapack error on fabric-1.4.1
<details>
    <summary>Error </summary>

[06:30:04] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "gg.moonflower.pollen.api.resource.modifier.ResourceModifierManager$SidedReloader.getCompleteFuture()" because "gg.moonflower.pollen.api.resource.modifier.ResourceModifierManager.serverReloader" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2124) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1972) ~[?:?]
	at net.minecraft.client.MinecraftClient.createWorld(MinecraftClient:1941) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen:286) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen:230) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:492) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:222) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1150) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "gg.moonflower.pollen.api.resource.modifier.ResourceModifierManager$SidedReloader.getCompleteFuture()" because "gg.moonflower.pollen.api.resource.modifier.ResourceModifierManager.serverReloader" is null
	at gg.moonflower.pollen.api.resource.modifier.ResourceModifierManager.getServerCompleteFuture(ResourceModifierManager.java:121) ~[pollen-fabric-1.4.1+1.18.2.jar:?]
	at net.minecraft.loot.LootManager.prepare(LootManager:1533) ~[?:?]
	at net.minecraft.resource.JsonDataLoader.prepare(JsonDataLoader:21) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18791(SinglePreparationResourceReloader:11) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

</details>


<details>
    <summary>Modlist</summary>

	- additionalbanners 7.0.4
	- adorn 3.5.0+1.18.2
	- advanced_runtime_resource_pack 0.5.7
	- all_the_fan_made_discs 0.2.4
	- ambientenvironment 7.0+19
	- ambientsounds 5.0.16
	- animatica 0.4+1.18
	- appleskin 2.4.0+mc1.18.2
	- aqupdcaracal 1.18.2-1.3.8
	- architects_palette 1.7
	- architectury 4.4.61
	- autoconfig1u 3.4.0
	- badpackets 0.1.2
	- balm-fabric 3.0.0+0
	- bedspreads 1.5.0-1.18
	- bendy-lib 2.0.4 via emotecraft
	- betterbiomeblend 1.18.2-1.3.4-fabric
	- betterf3 1.2.5
	- betterthirdperson 1.7.3
	- biomemakeover 1.18.2-1.4.23
	- blockstoparts 0.2.4+1.18.2 via vanilla_parts
	- blockus 2.4.5+1.18.2
	- blue_endless_jankson 1.2.1 via jankson
	- bookshelf 13.0.13
	- bricklayer 1.0.2-1.18.2-FABRIC
	- capybara 1.0.4
	- cardinal-components-base 4.1.4 via comforts
	- cardinal-components-entity 4.1.4 via comforts
	- cardinal-components-world 4.1.1 via coldsnaphorde
	- carrier 1.10.0
	- cartoonishhorde 0.3
	- catwalksinc 1.3.0
	- ce 1.1.5
	- charm 4.1.0
	- charmonium 4.0.0
	- chat_heads 0.6.0
	- chimes 1.1.1
	- chipped 1.2
	- chisel 1.4.5
	- chiselsandbits 1.2.87
	- chubby_stuff 1.0.1
	- citresewn 1.0.1+1.18.2
	- citresewn-defaults 1.0.1+1.18.2 via citresewn
	- cleardespawn 1.1.7
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.2.62
	- clumps 8.0.0+8
	- cobbled_paths 0.1.7
	- coldsnaphorde 1.2.4-1.18.2
	- collective-fabric 4.26
	- coloredglowlib 1.3.2
	- columns 1.4.0
	- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.10 via zoomify
	- com_github_ramanrajarathinam_native-utils 1.0.0 via screencopy
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- com_neovisionaries_nv-websocket-client 2.14 via figura
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- comforts 1.1.2-1.18.2
	- connectiblechains 2.1.1+1.18.2
	- consistency_plus 0.5.0+1.18.2
	- continuity 1.1.0+1.18.2
	- controlling 9.0+19
	- convenient-mobgriefing 2.0.2
	- cosmetica 1.1.1
	- create mc1.18.2_v0.4.1+586
	- createaddition ${version}
	- creative_library 1.1.0+1.18
	- creativecore 2.6.10
	- creatures_from_the_warmths 2.0.0+1.18.2
	- creeperoverhaul 1.3.1
	- crowdin-translate 1.4+1.18.2 via grid
	- dailydad_server 1.3.1
	- dark-loading-screen 1.6.11
	- darkpaintings 10.0.1
	- decorative_blocks 2.1.0
	- decorative_winter 2.1.0
	- dev_isxander_settxi 2.1.1 via zoomify
	- disable_custom_worlds_advice 2.0
	- display_case 1.0.0
	- doom 4.2.11
	- doubledoors-fabric 3.3
	- draggable-resource-packs 2.0.0
	- dripstone_fluid_lib 1.2.0 via milk
	- duckling 1.0.5
	- dummmmmmy 1.18-1.5.0
	- dustrial_decor 0.5
	- dynamicfps 2.1.0
	- dynamicsoundfilters 1.3.0+1.18.2
	- eatinganimationid 1.6
	- effective 1.2.1
	- emojitype 1.0.3
	- emotecraft 2.1.2
	- enchanted-vertical-slabs 1.4.1
	- endlessocean 0.2.5-BETA
	- enhancedblockentities 0.6+1.18.2
	- entity_texture_features 2.6.0
	- entityculling 1.5.1
	- exlinedoors 1.0.3
	- exlinefurniture 2.0.7
	- fabric 0.53.3+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via cosmetica
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.4+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-data-generation-api-v1 2.0.9+e19de87d60 via registrate-fabric
	- fabric-dimensions-v1 2.1.18+01a4d43d60 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.15+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.0+85719ab760 via fabric
	- fabric-item-groups-v0 0.3.12+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.4+kotlin.1.6.21
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.1+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.1+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via holograms
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.0+2afceb2960 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via cosmetica
	- fabric-transfer-api-v1 1.6.1+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.6
	- fake-player-api 0.3.0 via create
	- fallingleaves 1.11.1+1.18.2
	- farsight 1.18-1.9
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via collective-fabric
	- figura 0.0.8+1.18.2
	- fireworkfrenzy 1.9
	- flywheel 1.18-0.6.2.25 via create
	- forge_tags 2.1 via create
	- forgeconfigapiport 3.2.0
	- foxglow 1.2.8
	- friendsandfoes 1.3.4
	- frikandelbroodje 0.2
	- frogpog dev_0.7
	- gbfabrictools 1.3.4+1.18.2 via grid
	- geckolib3 3.0.42
	- glassdoor 2.1.0+1.18
	- goodall 1.0.2
	- goosik-config 0.2.0 via visuality
	- graveyard 1.8
	- grid 1.18.2-fabric0.47.10-1.6.6
	- highlighter 1.1.2
	- hologram-api 0.2.1+1.18-pre5 via holograms
	- holograms 1.3.1+1.18.2
	- hotbarswap 1.0.2
	- hyperlighting 1.2.3
	- iceberg 1.0.38
	- illuminations 1.10.4
	- immersive_weathering 2.4.0
	- impactfulweather 2.4.6
	- indium 1.0.3+mc1.18.2
	- io_github_imurx_arboard 1.1.0 via screencopy
	- iris 1.2.4-build.38
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- journeymap-api-fabric 1.18.2-1.8-fabric-SNAPSHOT via journeymap-fabric
	- journeymap-fabric 5.8.4
	- jsonem 0.1.1 via phonos
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- kiwi 6.0.2
	- kleeslabs 11.0.0
	- krypton 0.1.9
	- lazydfu 0.1.2
	- libblockattributes_core 0.10.2 via libmultipart_deps_container
	- libgui 5.3.1+1.18 via mocolors
	- libmultipart 0.7.2 via libmultipart_deps_container
	- libmultipart_deps_container 0.7.2 via vanilla_parts
	- libnetworkstack 0.6.0 via libmultipart_deps_container
	- libninepatch 1.1.0 via libgui
	- lightstones 1.6.0
	- litematica 0.11.3
	- lithium 0.7.10
	- lovely_snails 1.0.4+1.18
	- lucys_sloths 1.0-SNAPSHOT
	- malilib 0.12.1
	- mavm 1.0.7a
	- mcwbridges 2.0.3
	- mcwdoors 1.0.6
	- mcwfences 1.0.4
	- mcwlights 1.0.3
	- mcwpaintings 1.0.3
	- mcwtrpdoors 1.0.5
	- mcwwindows 2.0.3
	- me_hypherionmc_night-config_core 3.6.5_custom via hyperlighting
	- me_hypherionmc_night-config_toml 3.6.5_custom via hyperlighting
	- megane 7.5.1
	- megane-api 7.1.0 via megane
	- megane-fabric-transfer 7.1.0 via megane
	- megane-reborn-energy 7.0.0 via megane
	- megane-runtime 7.2.0 via megane
	- megane-vanilla 7.1.1 via megane
	- midnightlib 0.4.0
	- milk 0.3.2 via create
	- minecraft 1.18.2
	- minegate-moreblocks 1.2.1
	- minekea 2.7.1
	- mm 2.3 via porting_lib
	- mo_glass 1.6.1-MC1.18.2
	- mocolors 1.4.0
	- modid 3.2.0.0
	- modmenu 3.2.2
	- morebannerfeatures 1.1.3
	- moreblocksmod 0.1.9
	- morecarpets fabric-1.18.2-v1.0.1
	- morelogblocks 1.0.3
	- mousetweaks 2.22
	- moyai 1.18.2-1.1.0
	- multibeds 1.2.5
	- myron 1.6.3+1.18.1 via shetiphiancore
	- no-telemetry 1.3.0
	- noindium 1.0.1+1.18.2 via create
	- notenoughanimations 1.6.0
	- notenoughcrashes 4.1.6+1.18.2
	- notenoughcreativity 1.3.2
	- observable 2.2.3
	- omega-config 1.2.3-1.18.1 via noindium
	- orcinus 1.18.2-1.1.0
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_json_json 20211205 via pickyourpoison
	- org_luaj_luaj-jse 3.0.1 via figura
	- packet_tweaker 0.2.0+1.18-pre1 via server_translations_api
	- paintings 9.1.2.1
	- pehkui 3.3.1+1.14.4-1.19
	- pgen 1.0.1
	- phonos 0.3+1.18.2
	- pickupnotifier 3.2.0
	- pickyourpoison 1.0.7
	- pigeons 1.3.0
	- placeholder-api 1.1.3+1.17.1 via holograms
	- platforms 1.2.4
	- pling 1.5.0
	- plushies 1.2
	- polaroidcamera 1.2.6
	- porting_lib 1.1.0-beta+1.18.2-dev.ffa2ca8 via create
	- publicguiannouncement 3.2.0.1
	- puzzle 1.2.1
	- puzzle-base 1.2.1 via puzzle
	- puzzle-gui 1.2.1 via puzzle
	- puzzle-models 1.2.1 via puzzle
	- puzzle-splashscreen 1.2.1 via puzzle
	- puzzleslib 3.3.1
	- ratsmischief 1.3.7
	- reach-entity-attributes 2.1.1 via create
	- registrate-fabric MC1.18.2-1.0.3 via create
	- rocks 1.6.0
	- roughlyenoughitems 8.2.463
	- satin 1.7.2 via pickyourpoison
	- screencopy 1.1.0
	- searchlight 1.1.7
	- server_translations_api 1.4.9+1.18.2-rc1 via holograms
	- settxicloth 1.0.2 via zoomify
	- shetiphiancore 1.2.10
	- shroomlight_slab 1.2
	- signtools 1.0.0
	- sizeshiftingpotions 1.4.0
	- skinlayers 1.4.4-mc1.18.2
	- snowrealmagic 4.0.0
	- sodium 0.4.1+build.15
	- spruceui 3.3.0+1.17 via enhancedblockentities
	- sspb 2.0.0
	- starlight 1.0.2+fabric.89b8d9f
	- stonecutter_recipe_tags 3.0.1+1.18.bc850d5.fabric via consistency_plus
	- sulphate 1.0.2 via cosmetica
	- team_reborn_energy 2.2.0 via createaddition
	- terrablender 1.1.0.101
	- terraform-wood-api-v1 3.0.0 via blockus
	- theducksmod fabric-1182-11
	- tinyskeletons 3.2.1
	- tlcosmetica 0.4.0 via visuality
	- trinkets 3.3.1
	- twigs 1.1.3-patch1+1.18.2
	- vanilla_parts 2.0.1+1.18.2
	- visuality 0.4.2
	- voicechat 1.18.2-2.2.32
	- waterdripsound 1.18-0.3.0
	- waveycapes 1.2.0
	- waystones 2.5.3
	- wildfire_gender 2.9
	- worldedit 7.2.10+1742f98
	- worldedit_items 1.1.0
	- worldeditcui 1.18.2+01
	- wthit 4.10.3
	- yungsapi 1.18.2-Fabric-2.0.8
	- zoomify 1.6.0

</details>

**Comment by IAnon** [comment] 2022-06-03 18:08
Just conforming the same issue with Forge 40.1.31, MC 1.18.2, pollen-forge-1.4.1. Same error that Sooperfish posted.

**Comment by jacksonhardaway** [comment] 2022-06-04 09:33
See if this issue still occurs with Pollen 1.4.2, if it is I'll reopen.

**Comment by IAnon** [comment] 2022-06-04 20:11
Issue remains but with a different error.

https://pastebin.com/HpjZujQD

**Comment by jacksonhardaway** [comment] 2022-06-04 22:41
Issue still exists in Pollen 1.4.3

**Comment by StrangerSon71** [comment] 2022-06-13 20:42
Still happening. I do happen to have the Abnormals and Infernal betas installed.

**Comment by MissPotato** [comment] 2022-06-14 19:01
This also happens with only Pollen v1.4.3 and the library mod Placebo v6.4.0. I tested this on the latest forge 40.1.51 and the minimum forge version supported by placebo 40.1.14. https://mclo.gs/kjoWEHY

**Comment by jacksonhardaway** [comment] 2022-06-20 16:05
(hopefully) fixed in 1.4.4, let me know if it's still an issue and we'll look into it more

**Comment by jacksonhardaway** [comment] 2022-07-30 18:48
This is caused by a forge issue, update to the latest forge to fix

**Closed as completed by jacksonhardaway** 2022-07-30 18:48 UTC

**Comment by thelegitdolt** [comment] 2022-07-30 22:45
The W
