### ISSUE TITLE
Tier must be between 1 and 5

### ISSUE THREAD

**Issue by TheButterbrotMan** [MoonflowerTeam/pollen#13] opened 2022-03-01 00:20 UTC
### What version are you seeing the problem on?

1.18.x

### Describe the issue

```markdown
1. Install https://www.curseforge.com/minecraft/modpacks/deathdusk
2. Install Pollen
3. Create a World
```

### latest.log

```shell
java.lang.IllegalArgumentException: Tier must be between 1 and 5
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
	at org.apache.commons.lang3.Validate.exclusiveBetween(Validate.java:1181) ~[geckolib-fabric-1.18-3.0.33.jar:?]
	at gg.moonflower.pollen.common.trades.VillagerTradeManager.lambda$registerVillagerTrades$3(VillagerTradeManager.java:71) ~[pollen-fabric-1.1.1+1.18.1.jar:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapEntrySet.forEach(Int2ObjectOpenHashMap.java:1062) ~[fastutil-8.5.6.jar:?]
	at gg.moonflower.pollen.common.trades.VillagerTradeManager.registerVillagerTrades(VillagerTradeManager.java:70) ~[pollen-fabric-1.1.1+1.18.1.jar:?]
	at gg.moonflower.pollen.common.trades.VillagerTradeManager.init(VillagerTradeManager.java:33) ~[pollen-fabric-1.1.1+1.18.1.jar:?]
	at gg.moonflower.pollen.core.fabric.PollenFabric.lambda$onInitialize$18(PollenFabric.java:102) ~[pollen-fabric-1.1.1+1.18.1.jar:?]
	at gg.moonflower.pollen.api.event.events.lifecycle.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:11) ~[pollen-fabric-1.1.1+1.18.1.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.handler$jia001$preStart(IntegratedServer:1016) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer:72) ~[?:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:657) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by TheButterbrotMan** [comment] 2022-03-01 00:21
https://bytebin.lucko.me/utOviPaC9u

**Comment by TheButterbrotMan** [comment] 2022-03-01 00:26
https://github.com/MoonflowerTeam/pollen/issues/12

**Comment by TheButterbrotMan** [comment] 2022-03-01 00:26
https://github.com/MoonflowerTeam/pollen/issues/5

**Comment by TheButterbrotMan** [comment] 2022-03-01 00:29
Oh, you havent uploaded the fix to curseforge yet?

**Comment by Ocelot5836** [comment] 2022-03-02 20:49
I'm not sure if this issue is fixed yet. I'm reopening until the issue is 100% resolved.

**Comment by Ocelot5836** [comment] 2022-05-15 02:06
I'm closing this issue because it seems like no more issues have popped up with villager tiers.

**Closed as completed by Ocelot5836** 2022-05-15 02:06 UTC
