### ISSUE TITLE
Forge crash during load

### ISSUE THREAD

**Issue by Corvus20** [MoonflowerTeam/pollen#54] opened 2022-06-28 01:31 UTC
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
1. Have Pollen in mods folder
2. Have Pollen dependent mods (Anchor, Mannequin, Enhanced Mushrooms) in mods folder [This is optional, as it still crashes with just Pollen alone]
3. Have other mods in mods folder (Optional, as this does not seem to matter as far as I can tell. Nothing else really seems to be clashing in order to cause this crash)
4. Launch
5. Observe crash during loading process
```

### latest.log

```shell
Crash Report:
https://pastebin.com/0mmCjeE3


Latest Log:
https://pastebin.com/XcTt7dGV
```

**Comment by jacksonhardaway** [comment] 2022-06-28 01:34
Duplicate of #34

**Closed as completed by jacksonhardaway** 2022-06-28 01:34 UTC
